.\" Manpage for test161.
.\" Contact shaseley@buffalo.edu to correct errors or typos.
.TH man 1 "07 January 2017" "1.2.5" "test161 Manual"
.SH NAME
test161 \- OS/161 Testing Tool
.SH SYNOPSIS
test161 [ARGS]
.SH DESCRIPTION
.SH OPTIONS
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Scott Haseley (shaseley@buffalo.edu)
