.\" Manpage for test161-server.
.\" Contact shaseley@buffalo.edu to correct errors or typos.
.TH man 1 "07 January 2017" "1.2.5" "test161-server Manual"
.SH NAME
test161-server \- OS/161 Testing Tool
.SH SYNOPSIS
test161-server [ARGS]
.SH DESCRIPTION
.SH OPTIONS
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Scott Haseley (shaseley@buffalo.edu)
